apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleservice-book
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: book
  template:
    metadata:
      labels:
        bb: book
    spec:
      containers:
      - name: book-site
        image: exampleservice-book:0.0.1-SNAPSHOT
---
apiVersion: v1
kind: Service
metadata:
  name: book-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: book
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    bb: book
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090